### ISSUE TITLE
not working with deno

### ISSUE THREAD

**Issue by Tnifey** [HarryET/Arangeno#1]
in current state it not works on deno 1.0.2 / 1.0.3
`xhr` is one of bearer with deno support (and according to [issuecomment-502367556] (https://github.com/denoland/deno/issues/2191#issuecomment-502367556) ), 
we can rewrite xhr to fetch, but it's not optimal answer

i forked this repo and changed to state it's working on deno but I did not test it

[https://github.com/Tnifey/Arangeno/tree/feat/working-state](https://github.com/Tnifey/Arangeno/tree/feat/working-state)

**Comment by HarryET** [comment]
Hey, send a PR and I'll merge it

**Comment by HarryET** [comment]
Also I knew it wouldn't work as I never finished converging it from Nodejs as I didn't have enough time and it's great you had a chance to!

**Comment by HarryET** [comment]
Merged! Thx for pr

**Comment by Tnifey** [comment]
fixed by #4
